### ISSUE TITLE
Multiplayer are laggy

### ISSUE THREAD

**Issue by LatvianPotatoFarmer** [montax/CDRE#18]
Multiplayer is laggy: a lot of touch lags, particularly in janes mod v2 extra nitro games (mostly hits in the back)
Also when there is someone with ping like over 100 or just lagging its almost impossible to stole his flag, hits arent working on him

**Comment by LatvianPotatoFarmer** [comment]
https://www.youtube.com/watch?v=D-vTXdEAUKc - touch lags explanation

**Comment by abadguy1** [comment]
Fixed in 1.5.27
