### ISSUE TITLE
Downloading maps / mods issue

### ISSUE THREAD

**Issue by LatvianPotatoFarmer** [montax/CDRE#22]
Downloading mods and maps sometimes doesn't work correctly
"Error downloading map"
or just crash

**Comment by montax** [comment]
Does the crash have any useful message? If is "An unhandled exception has occured" please provide us the .dmp file.

Thank You!

**Comment by LatvianPotatoFarmer** [comment]
Sometimes it shows "an unhandled exception has occured" and it doesn't leave an dmp file.
When "error downloading map" happens it shows in-game, game doesnt crash

**Comment by LatvianPotatoFarmer** [comment]
![crashday 2017-08-19 20-18-12-23](https://user-images.githubusercontent.com/31080350/29488848-bd12a722-851b-11e7-9621-786b7ce2dae9.jpg)

**Comment by montax** [comment]
Fixed in 1.5.25.
