### ISSUE TITLE
Bug with car in SP

### ISSUE THREAD

**Issue by LatvianPotatoFarmer** [montax/CDRE#24]
For some reason every time I restart the game my default car set as "buster gst" although i set the incubator last time i quit the game.
Noticed it in track editor in test drive.
(Also before that happpen i turned off janes mod v2 in mod dialog, this could cause such a bug, but not sure)

**Comment by montax** [comment]
I could not reproduce it. Does it happens in Single Event aswell?

**Comment by LatvianPotatoFarmer** [comment]
I think its about janes mod v2 so you can close this issue
