### ISSUE TITLE
No stats after the race, rather than time

### ISSUE THREAD

**Issue by GarryGREY** [montax/CDRE#25]
After the race, it shows stats with 0 m driven and 0 kph average and max speed (for both player and AI opponents). Tested in both Career and Quick Race. Happens every single time. No mods installed
Pretty sure, it was working before...
![20170817171835_1](https://user-images.githubusercontent.com/31103182/29416849-6f29636a-8378-11e7-9f5f-64bf0e2b3b0c.jpg)
![20170817175858_1](https://user-images.githubusercontent.com/31103182/29416850-6f2d6e7e-8378-11e7-9c13-69978f8eb7c0.jpg)

p.s. also, got 0 minigun hits/accuarcy once, but can't reproduce it

UPD: Same with Test Drive mode. So I assume, all game modes are affected. Odometer doesn't work in-game either and stuck at 84kms. However, progress on "Around the world" achievement updating with no problem (currently at 3.8k kms)

**Comment by montax** [comment]
Thank you for the report!

**Comment by montax** [comment]
![fix](https://user-images.githubusercontent.com/20192886/29689120-580d4336-8922-11e7-9d23-b4620025e3a6.png)

Should works now! (1.5.24)
