### ISSUE TITLE
Clan tags not updated in game

### ISSUE THREAD

**Issue by Nummer** [montax/CDRE#28]
Clan tags not updated in game. 
![image](https://user-images.githubusercontent.com/7760838/29429637-0e2584f0-839a-11e7-8464-c9a4610fd401.png)
![image](https://user-images.githubusercontent.com/7760838/29429648-13424db0-839a-11e7-9cd0-fa836d0bf688.png)

**Comment by Nummer** [comment]
i change clan tag in group. Game not updated tag.

**Comment by abadguy1** [comment]
clantag updates after the next game execution or by changing the clantag option.

**Comment by Nummer** [comment]
@abadguy1 not updated. Lol

**Comment by abadguy1** [comment]
Ok, basically Steam updates the clan tag every 12 hours. It's a steam API problem.
