### ISSUE TITLE
Space between the clan tag and nickname ?

### ISSUE THREAD

**Issue by Nummer** [montax/CDRE#29]
![image](https://user-images.githubusercontent.com/7760838/29429637-0e2584f0-839a-11e7-8464-c9a4610fd401.png)
not have space char =\

**Comment by abadguy1** [comment]
Just type the space in the group clantag. Also type \d as colour terminator

**Comment by Nummer** [comment]
@abadguy1 lol. Please, add space, and auto add \7 on end clan tag. Clan tag change nickname colors. Lol
