### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by LatvianPotatoFarmer** [montax/CDRE#39]
Got crashed with the following error message:
![vilet](https://user-images.githubusercontent.com/31080350/29490835-4fcbadb8-8551-11e7-92dc-b05c37cf2473.png)

All i did is invited friend to friend's host then closed the invitation window and back to the game

no dmp file

**Comment by abadguy1** [comment]
Fixed in 1.5.26 (Still may happen in some other different situations, should be reported from time to time)
