### ISSUE TITLE
Bugs in multiplayer

### ISSUE THREAD

**Issue by LatvianPotatoFarmer** [montax/CDRE#46]
Sometimes ready state doesn't sync between players
![20170824233208_1](https://user-images.githubusercontent.com/31080350/29687428-19483fae-8925-11e7-96c2-080740b2324f.jpg)
Or some players in lobby and some players are still racing

**Comment by abadguy1** [comment]
@LatvianPotatoFarmer what is the state of that guy?

**Comment by LatvianPotatoFarmer** [comment]
He showed as idle but he was actually ready

**Comment by abadguy1** [comment]
I think he got in-game and the lobby said it was in iddle. It got fixed in 1.5.25 if that's the case. We will re-open the ticket in case it appears.
