### ISSUE TITLE
Error happens to a lot of people

### ISSUE THREAD

**Issue by LatvianPotatoFarmer** [montax/CDRE#59]
Prevent the game from running and being solved by verifying integrity cache in app properties
![xfdjnskhw94](https://user-images.githubusercontent.com/31080350/29897182-643dc6d8-8de8-11e7-8598-b1734369e5e5.jpg)

**Comment by abadguy1** [comment]
We can only verify the files integrity from our game, but we can not force the game to auto update or to fix itself. To solve these kind of problems the user should manually do a cache verification from the game properties.

**Comment by cosmy1** [comment]
This error happens when someone modify original Crashday archives. Instead of editing them people have to create new .cpk archives and use the current modding system either by using mod testing or uploading them on Steam Workshop.

**Comment by montax** [comment]
This error happens when someone modify original Crashday archives. Instead of editing them people have to create new .cpk archives and use the current modding system either by using mod testing or uploading them on Steam Workshop.
